### ISSUE TITLE
Cascade onboarding June 11th

### ISSUE THREAD

**Issue by SteveCleanBrook** [rpcpool/ping-thing-client#8]
Metaplex
https://customers.triton.one/accounts/ac79b493-493b-4cbb-8bb7-2d6e0a6070b3
100 PPS

Upgrade HMSoft to 200
https://customers.triton.one/accounts/80118a01-b125-4ebd-ae41-f8073b83b3ca
200

**Comment by SteveCleanBrook** [comment]
Swissborg (might have it already)
https://customers.triton.one/accounts/98903122-63c8-4376-86bc-a01ed9582b40
100PPS

**Comment by dllegru** [comment]
done after checking with Steve here
https://github.com/rpcpool/rpcpool/pull/9265
